### ISSUE TITLE
TIMESTAMP_UPR negative value? 

### ISSUE THREAD

**Issue by NevadaMark** [ajn96/iSensor-SPI-Buffer#9]
Should the minimum value of the TIMESTAMP_UPR register be zero or is this a twos complement number?  Thank you! 
https://github.com/ajn96/iSensor-SPI-Buffer/blob/master/REGISTER_DEFINITION.md#TIMESTAMP_UPR

![TIMESTAMP_UPR_1](https://user-images.githubusercontent.com/12829744/88537675-fe551e00-cfdb-11ea-98fc-b6a9124425cb.PNG)

**Comment by ajn96** [comment]
Hi Mark,

The timestamp register is unsigned, 32-bits. The negative is due to an offset applied by the FX3 data plotting GUI by the "autonull" functionality. I had autonulled the plot to make it easier to see both signals.

I'll generate a new plot with the offset set to 0 for the timestamp, to avoid potential confusion.

**Comment by ajn96** [comment]
Updated image
